name: Dart Code Metrics

on: [push]

jobs:
  check:
    name: dart-code-metrics-action

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: '3.3.4'
      #     channel: 'stable'
      #     cache: true
      #     cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      #     # cache-path: ${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:
      # - run: flutter --version

      - name: dart-code-metrics
        uses: dart-code-checker/dart-code-metrics-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_comment: true
